Update deployment-configuration.yml

diff --git a/.github/workflows/deployment-configuration.yml b/.github/workflows/deployment-configuration.yml
--- a/.github/workflows/deployment-configuration.yml
+++ b/.github/workflows/deployment-configuration.yml
@@ -1,18 +1,36 @@
-# Git workflow file for setting environment and deployment
-
-name: Deploy to ECS Fargate
+# Git workflow file for deployment to QA and Staging environment
+name: Deployment Configuration Dispatch - AWS ECS
+run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }}
 
 on:
-  workflow_call:
+  workflow_dispatch: # This workflow will run manually
+    inputs:
+      environment:
+        description: ' Drowpdown to select environment for deployment.'
+        required: true
+        type: environment
 
 jobs:
-  deploy:
+  environment_validation:
     runs-on: ubuntu-latest
 
-    environment:
-      name: ${{ github.event.workflow_run.outputs.environment }}
-
+    # outputs:
+    #   environment: ${{ steps.setting_value.outputs.environment }}
     steps:
-      - name: Deployment Info
-        run: echo "Starting Deployment for Environment => ${{ github.event.workflow_run.outputs.environment }}"
-      
+      #  We will do this validation if environment is not a type of environment
+      # - name: Validate Environment Input
+      #   id: validate_input
+      #   run: |
+      #     chosen_environment=${{ github.event.inputs.environment }}
+      #     if [ $chosen_environment != "QA" ] && [ $chosen_environment != "STAGING" ]; then
+      #       echo "Invalid environment. Please choose either QA or STAGING."
+      #       exit 1
+      #     fi
+      #     echo "Input environment ${{ github.event.inputs.environment }} is valid."
+      - name: Environment
+        id: environment
+        run: echo "Starting Deployment for Environment => ${{ github.event.inputs.environment }}"
+      - name: Start Deployment Workflow
+        uses: ./.github/workflows/deployment-aws.yml
+        with:
+          environment: ${{ github.event.inputs.environment }}
